# Programación para *Data Science*

## Unidad 6: Preprocesamiento de datos en Python

# Introducció

En este Notebook encontraréis dos conjuntos de ejercicios: un primer conjunto de **ejercicios para practicar** y un segundo conjunto de **actividades evaluables** como PEC de la asignatura.

En cuanto al conjunto de ejercicios para practicar, éstos no puntúan para la PEC, pero os recomendamos que los intentéis resolver como parte del proceso de aprendizaje. Encontraréis ejemplos de posibles soluciones a los ejercicios al propio notebook, pero es importante que intentéis resolverlos vosotros antes de consultar las soluciones. Las soluciones os permitirán validar vuestras respuestas, así como ver alternativas de resolución de las actividades. También os animamos a preguntar cualquier duda que surja sobre la resolución de los **ejercicios para practicar** en el foro del aula.

En relación a las actividades evaluables, veréis que cada una de ellas tiene asociada una puntuación que indica el peso que tiene la actividad sobre la nota de la PEC. Adicionalmente, hay un ejercicio opcional, que no tiene puntuación dentro de la PEC, pero que se valora al final del semestre de cara a conceder las matrículas de honor y redondear las notas finales. Podéis sacar la máxima nota de la PEC sin necesidad de hacer este ejercicio! El objetivo de este ejercicio es que sirva como pequeño reto para los estudiantes que quieran profundizar en el contenido de la asignatura.

Además, veréis que todas las actividades tienen una etiqueta que indica los recursos necesarios para llevarla a cabo. Hay tres posibles etiquetas:

* <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">NM</span> **Sólo materiales**: las herramientas necesarias para realizar la actividad se pueden encontrar en los materiales de la asignatura. 

* <span style="font-family: Courier New; background-color: #ffcc5c; color: #000000; padding: 3px; ">EG</span> **Consulta externa guiada**: la actividad puede requerir hacer uso de herramientas que no se encuentran en los materiales de la asignatura, pero el enunciado contiene indicaciones de dónde o cómo encontrar la información adicional necesaria para resolver la actividad.

* <span style="font-family: Courier New; background-color: #f2ae72; color: #000000; padding: 3px; ">EI</span> **Consulta externa independente**: la actividad puede requerir hacer uso de herramientas que no se encuentran en los materiales de la asignatura, y el enunciado puede no incluir la descripción de dónde o cómo encontrar esta información adicional. Será necesario que el estudiante busque esta información utilizando los recursos que se han explicado en la asignatura.

Es importante notar que estas etiquetas no indican el nivel de dificultad del ejercicio, sino únicamente la necesidad de consulta de documentación externa para su resolución. Además, recordad que las **etiquetas son informativas**, pero podréis consultar referencias externas en cualquier momento (aunque no se indique explícitamente) o puede ser que podáis hacer una actividad sin consultar ningún tipo de documentación. Por ejemplo, para resolver una actividad que sólo requiera los materiales de la asignatura, puedéis consultar referencias externas si queréis, ya sea tanto para ayudaros en la resolución como para ampliar el conocimiento!

En cuanto a la consulta de documentación externa en la resolución de los ejercicios, recordad **citar siempre la bibliografía utilizada** para resolver cada actividad.

## Ejercicios para practicar

**Los siguientes 3 ejercicios no puntúan para la PEC**, pero os recomendamos que los intentéis resolver antes de pasar a los ejercicios propios de la PEC. También encontraréis las soluciones a estos ejercicios al final del Notebook.

## Ejercicio 1

Cargue los datos del fichero `bank_edited.csv` en un dataframe. Este conjunto de datos recoge información respecto a una campaña de marketing de un banco portugués. El conjunto original se puede encontrar en el [repositorio de datos de Machine Learning de la UC Irvine] (http://archive.ics.uci.edu/ml/datasets/Bank+Marketing), pero el conjunto que utilizaremos tiene alguna modificación .

Observación: revise la documentación de la función [ `read_csv`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) para ver qué parámetro disponemos para ajustar el proceso de cargar de datos.

Los valores del estado civil (atributo `marital`) contienen errores tipográficos y incluyen el uso de diferentes nomenclaturas. En este ejercicio unificaremos la nomenclatura de los valores de esta variables.<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">NM</span> 

a) ¿Cuantos valors diferentes tiene el atributo `marital` en el conjunto de datos? Mostrad estos valores.

In [58]:
# Respuesta
import pandas as pd

data = pd.read_csv("data/bank_edited.csv", sep= ";")
data.head(n=5)
#vals = set(data["marital"])
#print("Hay {} Valores distintos:\n{}\n".format (len(vals),vals))

vals2 = data.marital.unique()
print("Hay {} Valores distintos:\n{}".format (len(vals2),vals2))

Hay 11 Valores distintos:
['married' 'single' 'marrid' 'divorced' 'maried' 'sing' 'Married'
 'MARRIED' 'DIVORCED' 'Single' 'SINGLE']

 b) Unificad los atributos `marital` en los valores: "single", "married" o "divorced".

In [121]:
# Respuesta

data.loc[(data.marital == "SINGLE") | (data.marital == "Single") | (data.marital == "sing"), ["marital"]] = "single"

data.loc[(data.marital == "MARRIED") | (data.marital == "Married") | (data.marital == "maried") 
         | (data.marital == "marrid"), ["marital"]] = "married"

data.loc[(data.marital == "DIVORCED"), ["marital"]] = "divorced"

#set(data["marital"])
print(data.marital.unique())

['married' 'single' 'divorced']

c) ¿Qué columnas contienen valores perdidos?

In [60]:
# Respuesta
#def is_null(x):
#    return any(pd.isnull(x))
#print(data.apply(is_null))
print(data.isna().any())

age          False
job          False
marital      False
education    False
default      False
balance       True
housing      False
loan         False
contact      False
day           True
month        False
duration      True
campaign     False
pdays        False
previous     False
poutcome     False
y            False
dtype: bool

d) Calculad el primer y el tercer cuartil del atributo "balance".

In [106]:
# Respuesta

print((data['balance'].quantile(0.25)))
print(data['balance'].quantile(0.75))

68.0
1476.0

## Ejercicio 2

El atributo `poutcome` contiene información sobre si el cliente del banco contractó un deposito. Calula la correlacióm entre el atributo `poutcome` y el resto de atributos (usa la función ['corr'](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.corr.html)). ¿Qué variable presenta mayor correlación con `poutcome`?<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">NM</span>

In [135]:
# Respuesta

import pandas as pd
import numpy as np
#import warnings

#Mi método, binarizando todas las columnas con valores categóricos
datatrans = pd.get_dummies(data, columns = ["job", "marital", "education", "default", "housing", 
                                            "loan", "contact", "month", "poutcome", "y"], dummy_na = True)
print(list(datatrans))
print(datatrans.corr()["poutcome_success"])

#Método 2
# Seleccionamos únicamente la muestras que contienen  información no precisa sobre el ciente contrató o no el depósito

data_pout = data[data.poutcome.isin(("failure","success"))]


# Discretizamos la columna poutcome para poder calcular la correlación 

data_pout['poutcome_cat'] = data_pout.poutcome.astype("category").cat.codes

# Calculamos la correlación con el resto de columnas 

data_pout.corr()["poutcome_cat"]

['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous', 'job_admin.', 'job_blue-collar', 'job_entrepreneur', 'job_housemaid', 'job_management', 'job_retired', 'job_self-employed', 'job_services', 'job_student', 'job_technician', 'job_unemployed', 'job_unknown', 'job_nan', 'marital_divorced', 'marital_married', 'marital_single', 'marital_nan', 'education_primary', 'education_secondary', 'education_tertiary', 'education_unknown', 'education_nan', 'default_no', 'default_yes', 'default_nan', 'housing_no', 'housing_yes', 'housing_nan', 'loan_no', 'loan_yes', 'loan_nan', 'contact_cellular', 'contact_telephone', 'contact_unknown', 'contact_nan', 'month_apr', 'month_aug', 'month_dec', 'month_feb', 'month_jan', 'month_jul', 'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct', 'month_sep', 'month_nan', 'poutcome_failure', 'poutcome_other', 'poutcome_success', 'poutcome_unknown', 'poutcome_nan', 'y_no', 'y_yes', 'y_nan']
age                 0.048626
balance             0.030550
day                -0.027933
duration            0.049234
campaign           -0.058268
                      ...
poutcome_unknown   -0.365185
poutcome_nan             NaN
y_no               -0.283481
y_yes               0.283481
y_nan                    NaN
Name: poutcome_success, Length: 63, dtype: float64

age             0.090540
balance         0.039791
day             0.009252
duration        0.142385
campaign       -0.059986
pdays          -0.276853
previous        0.023411
poutcome_cat    1.000000
Name: poutcome_cat, dtype: float64

## Ejercicio 3

El módulo sklearn incluye varios datasets de ejemplo, dentro del módulo `sklearn.datasets`. Estos datasets se almacenan en formato `Bunch`, propio de sklearn. Un `Bunch` es un objeto tipo diccionario, los atributos interesantes son: `data`, con los datos en crudo, `target`, con generalmente las etiquetas de clasificación o etiquetas objetivo, `target_names`, el significado de las etiquetas, `feature_names`, el significado de las características o atributos, `DESCR` , la descripción completa del conjunto de datos.

Importa el dataset `iris` de `sklearn`. Almacena los datos este dataset como un objeto `pandas`, con los correpondientres nombres de variables. Añade la variable `target` en el dataframe con el nombre de atributo `Species` y los valors con el tipo de especie de cada muestra.<span style="font-family: Courier New; background-color: #ffcc5c; color: #000000; padding: 3px; ">EG</span>

In [270]:
# Respuesta

#Importamos librerias
from sklearn import datasets
import pandas as pd

iris_bunch = datasets.load_iris()
#print(iris_bunch)
iris_pandas = pd.DataFrame(iris_bunch['data'],columns=iris_bunch['feature_names'])
#print(iris_pandas.tail())
iris_pandas['Species'] = iris_bunch['target_names'][iris_bunch['target']]
#print(iris_pandas.tail())
#print((iris_bunch['target_names']).shape)
#print((iris_bunch['target']).shape)
#print(iris_bunch['target_names'][iris_bunch['target']])

# Ejercicios para la PEC

A continuación, los **ejercicios y preguntas teóricas que debe completar en esta PEC** y que forman parte de la evaluación de esta unidad.

# Ejercicio 1

Importa el fichero `siri.csv` de la carpeta de datos. En ella encontrarás notas (en un rango de 0 a 10) correspondientes a estudiantes de tres escuelas diferentes para cuatro asignaturas. Una vez importados los datos, realiza las siguientes operaciones:

a) Muestra por pantalla una lista de las diferentes escuelas en los datos. En caso no observar tres escuelas por errores tipográficos, mayúsculas y otros, corrige la nomenclatura para homogeneizar una columna con las tres escuelas. 


**(1 punto)**  <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [3]:
# Respuesta

#Importamos libreria
import pandas as pd

#Cargo los datos
dfsiri = pd.read_csv("data/siri.csv")

#Observo los primeros ejemplos con sus campos
dfsiri.head()

#Unifico los campos
dfsiri.loc[(dfsiri.school == "Summer") | (dfsiri.school == "sumer") | (dfsiri.school == "ummer") 
           | (dfsiri.school == "Sumer"), ["school"]] = "summer"
dfsiri.loc[(dfsiri.school) == "Winter", ["school"]] = "winter"
dfsiri.loc[(dfsiri.school == "Spring") | (dfsiri.school == "Sprng"), ["school"]] = "spring"

#Muestro la lista por pantalla
print("Listado de las diferentes escuelas:\n\n{}".format(list(dfsiri.school.unique())))

Listado de las diferentes escuelas:

['summer', 'winter', 'spring']


b) Buscar notas claramente anómalas. En caso de encontrar notas anómalas sustitúyelas por NaN.


**(1 punto)**  <span style="font-family: Courier New; background-color: #f2ae72; color: #000000; padding: 3px; ">EI</span>

In [4]:
# Respuesta
#https://living-sun.com/es/python/706511-how-to-make-complex-data-cleaning-in-pandas-python-pandas-dataframe.html
#https://www.geeksforgeeks.org/python-pandas-dataframe-round/
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

#Importamos librerias
import pandas as pd
import numpy as np

#Miro los atributos
print("Miro las cabeceras: {}".format(list(dfsiri)))


#Miro valores unicos de cada atributo
print('\n\nValores iniciales de maths\n\n', dfsiri.maths.unique())
print('\n\nValores iniciales de literature\n\n', dfsiri.literature.unique())
print('\n\nValores iniciales de physics\n\n', dfsiri.physics.unique())
print('\n\nValores iniciales de history\n\n', dfsiri.history.unique(), '\n\n')


#Miro estadísticas y veo que hay dos valores máximos que no deberían estar ahí (50.4 y 101.4). Se puede ver que 
#las desviaciones estándar son del 50% y 100% respecto a sus medias 
print("Miro las estadísticas iniciales\n\n{}\n\n".format(dfsiri.describe()))

#Aplico el condicionante para encontrarlos y su sustitución por NaN, a la vez:
dfsiri.loc[(dfsiri.maths) > 10, "maths"] = np.nan
dfsiri.loc[(dfsiri.literature > 10), "literature"] = np.nan
dfsiri.loc[(dfsiri.physics > 10), "physics"] = np.nan
dfsiri.loc[(dfsiri.history > 10), "history"] = np.nan


#Visualizo
print('\n\nValores finales de maths\n\n', dfsiri.maths.unique())
print('\n\nValores finales de literature\n\n', dfsiri.literature.unique())
print('\n\nValores finales de physics\n\n', dfsiri.physics.unique())
print('\n\nValores finales de history\n\n', dfsiri.history.unique(), '\n\n')
print("Miro las estadísticas finales\n\n{}".format(dfsiri.describe()))

Miro las cabeceras: ['maths', 'literature', 'physics', 'history', 'school']


Valores iniciales de maths

 [ 5.1  4.9  4.7  4.6  5.  50.4  4.4  5.4  4.8  4.3  5.8  5.7  5.2  5.5
  4.5  5.3  7.   6.4  6.9  6.5  6.3  6.6  5.9  6.   6.1  5.6  6.7  6.2
  6.8  7.1  7.6  7.3  7.2  nan  7.7  7.4  7.9]


Valores iniciales de literature

 [3.5 3.  3.2 3.1 3.6 3.9 3.4 2.9 3.7 4.  4.4 3.8 3.3 4.1 4.2 nan 2.3 2.8
 2.4 2.7 2.  2.2 2.5 2.6]


Valores iniciales de physics

 [  1.4   1.3   1.5   nan   1.6   1.1   1.2   1.7   1.    1.9 101.4   4.7
   4.5   4.9   4.    4.6   3.3   3.9   3.5   4.2   3.6   4.4   4.1   4.8
   4.3   5.    3.8   3.7   5.1   3.    6.    5.9   5.6   5.8   6.6   6.3
   6.1   5.3   5.5   6.7   6.9   5.7   5.4   5.2]


Valores iniciales de history

 [0.2 0.4 0.3 0.1 0.5 0.6 1.4 1.5 1.3 1.6 1.  1.1 1.8 nan 1.2 1.7 2.5 1.9
 2.1 2.2 2.  2.4 2.3]


Miro las estadísticas iniciales

            maths  literature     physics     history
count  148.000000  144.000000  145.000000  148.000000
mean     6.125676    3.064583    4.461379    1.193243
std      3.752716    0.440354    8.290475    0.764489
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.325000    5.100000    1.800000
max     50.400000    4.400000  101.400000    2.500000




Valores finales de maths

 [5.1 4.9 4.7 4.6 5.  nan 4.4 5.4 4.8 4.3 5.8 5.7 5.2 5.5 4.5 5.3 7.  6.4
 6.9 6.5 6.3 6.6 5.9 6.  6.1 5.6 6.7 6.2 6.8 7.1 7.6 7.3 7.2 7.7 7.4 7.9]


Valores finales de literature

 [3.5 3.  3.2 3.1 3.6 3.9 3.4 2.9 3.7 4.  4.4 3.8 3.3 4.1 4.2 nan 2.3 2.8
 2.4 2.7 2.  2.2 2.5 2.6]


Valores finales de physics

 [1.4 1.3 1.5 nan 1.6 1.1 1.2 1.7 1.  1.9 4.7 4.5 4.9 4.  4.6 3.3 3.9 3.5
 4.2 3.6 4.4 4.1 4.8 4.3 5.  3.8 3.7 5.1 3.  6.  5.9 5.6 5.8 6.6 6.3 6.1
 5.3 5.5 6.7 6.9 5.7 5.4 5.2]


Valores finales de history

 [0.2 0.4 0.3 0.1 0.5 0.6 1.4 1.5 1.3 1.6 1.  1.1 1.8 nan 1.2 1.7 2.5 1.9
 2.1 2.2 2.  2.4 2.3]


Miro las estadísticas finales

            maths  literature     physics     history
count  147.000000  144.000000  144.000000  148.000000
mean     5.824490    3.064583    3.788194    1.193243
std      0.813549    0.440354    1.744221    0.764489
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.325000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000


c) Encuentra los valores perdidos. Imputa los valores perdidos por la media de los datos por columna 


**(0.5 puntos)**  <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [5]:
# Respuesta

#Importamos librerias
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

# Sustituiremos los valores perdidos por la media de la columna 
imp = SimpleImputer(strategy='mean')

#Buscamos las columnas con na
print("Columnas iniciales con nan\n\n{}".format(dfsiri.isna().any()))

# Aplicamos la transformación a las columnas afectadas
dfsiri["maths"] = imp.fit_transform(dfsiri[["maths"]]).ravel()
dfsiri["literature"] = imp.fit_transform(dfsiri[["literature"]]).ravel()
dfsiri["physics"] = imp.fit_transform(dfsiri[["physics"]]).ravel()
dfsiri["history"] = imp.fit_transform(dfsiri[["history"]]).ravel()

Columnas iniciales con nan

maths          True
literature     True
physics        True
history        True
school        False
dtype: bool

d) Comprueba que ya no hay valores perdidos en el objeto pandas. 

**(0.5 puntos)**  <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [664]:
# Respuesta

print("Columnas finales con nan\n\n{}".format(dfsiri.isna().any()))

Columnas finales con nan

maths         False
literature    False
physics       False
history       False
school        False
dtype: bool

## Ejercicio 2


En este ejercicio trabajaremos un conjunto de datos que se derivó del censo estadounidense de 1990, utilizando una fila por censo
dentro de un grupo de viviendas o bloques. Un grupo de bloques es la unidad geográfica más pequeña para la que La Oficina del Censo de  EE.UU.
publica datos de muestra (un grupo de bloques generalmente tiene una población
de 600 a 3,000 personas).


  - Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
      Statistics and Probability Letters, 33 (1997) 291-297

a) Generar un objeto `pandas` de nombre `housings` con los datos que genera la función `datasets.fetch_california_housing()` dentro de `sklearn`. El objeto debe contener todas las variables del conjunto de datos incluida una columna con los valores de  `Prices` (target). 


**(1 punto)**  <span style="font-family: Courier New; background-color: #ffcc5c; color: #000000; padding: 3px; ">EG</span>

In [7]:
# Respuesta
#https://stackoverflow.com/questions/38105539/how-to-convert-a-scikit-learn-dataset-to-a-pandas-dataset

#Importamos librerias
import pandas as pd
import numpy as np
from sklearn import datasets

#Cargamos fichero
cali_house_bunch = datasets.fetch_california_housing()
#print(cali_house_bunch)

#Creamos dataframe
housings = pd.DataFrame(cali_house_bunch.data, columns=cali_house_bunch.feature_names)
#print(housings.head())

#Añadimos la columna prices con las "labels", en este caso los precios de las viviendas
housings['Prices'] = cali_house_bunch['target']
housings.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Prices
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

b) Obtener, los nombres de las variables, el número total de filas y columnas, y comprobar la posible existencia de valores perdidos en los datasets. Obtener la media, desviación típica, valores máximos y mínimos de todas las variables del data frame.


**(0.5 puntos)**  <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [8]:
# Respuesta

#Directamente imprimimos todo lo que nos piden
print("Las variables son\n\n{}\n\n".format(list(housings)))
print("Hay {} filas y {} columnas\n\n".format(len(housings),len(housings.columns)))
print("Posibles valores faltantes (no hay): \n\n{}\n\n". format(housings.isna().any()))
print("Visualizamos una tabla con las estadísticas:\n\n{}".format(housings.describe()))

Las variables son

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude', 'Prices']


Hay 20640 filas y 9 columnas


Posibles valores faltantes (no hay):

MedInc        False
HouseAge      False
AveRooms      False
AveBedrms     False
Population    False
AveOccup      False
Latitude      False
Longitude     False
Prices        False
dtype: bool


Visualizamos una tabla con las estadísticas:

             MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000
mean       3.870671     28.639486      5.429000      1.096675   1425.476744
std        1.899822     12.585558      2.474173      0.473911   1132.462122
min        0.499900      1.000000      0.846154      0.333333      3.000000
25%        2.563400     18.000000      4.440716      1.006079    787.000000
50%        3.534800     29.000000      5.229129      1.048780   1166.000000
75%        4.743250     37.000000      6.052381      1.099526   1725.000000
max       15.000100     52.000000    141.909091     34.066667  35682.000000

           AveOccup      Latitude     Longitude        Prices
count  20640.000000  20640.000000  20640.000000  20640.000000
mean       3.070655     35.631861   -119.569704      2.068558
std       10.386050      2.135952      2.003532      1.153956
min        0.692308     32.540000   -124.350000      0.149990
25%        2.429741     33.930000   -121.800000      1.196000
50%        2.818116     34.260000   -118.490000      1.797000
75%        3.282261     37.710000   -118.010000      2.647250
max     1243.333333     41.950000   -114.310000      5.000010

c) Calcula la correlación de la variable `Prices` con el resto de variables. Ordena el vector de correlaciones de mayor a menor en valor absoluto. ¿Qué variable aparece con más correlación con los precios? Interpreta los resultados.


**(0.5 puntos)**  <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [9]:
# Respuesta

#Importamos libreria
import pandas as pd

#En este caso no hay atributos con valores categóricos, así que no realizamos ninguna transformación adicional
housings.corr()["Prices"].abs().sort_values(ascending=False) 

#El precio de la vivienda tiene una correlación alta respecto a MedInc. El resto de atributos influyen menos
#MedInc representa los ingresos medios de la vivienda en un bloque de viviendas -->
#https://www.kaggle.com/camnugent/california-housing-prices

Prices        1.000000
MedInc        0.688075
AveRooms      0.151948
Latitude      0.144160
HouseAge      0.105623
AveBedrms     0.046701
Longitude     0.045967
Population    0.024650
AveOccup      0.023737
Name: Prices, dtype: float64

## Ejercicio 3

Con la mismo dataset anterior:

a) Con cada una de las variables `Latitude` y `Longitude`, crea dos variables discretizadas con 10 segmentos, de forma que:

- en las primeras cada intervalo contenga el mísmo número de muestras (equidensidad por segmento) en (`qLat`, `qLon`) 
- en las segundas cada intervalo tengan la misma longitud de intervalo (equidistancia por segmento) en (`sLat`,`sLon`) 


**(1 punto)**  <span style="font-family: Courier New; background-color: #f2ae72; color: #000000; padding: 3px; ">EI</span>

In [10]:
# Respuesta
#https://pbpython.com/pandas-qcut-cut.html

#Importamos librerias
import pandas as pd

housings["qLat"] = pd.qcut(housings["Latitude"], q=10)
housings["qLon"] = pd.qcut(housings["Longitude"], q=10)
housings["sLat"] = pd.cut(housings["Latitude"], 10)
housings["sLon"] = pd.cut(housings["Longitude"], 10)

b) Observa la distribución en las variables discretizadas calculando el número de muestras dentro de cada intérvalo. Podéis mirar el método de pandas .value_counts() para contar valores de cada grupo. 

**(0.5 puntos)** <span style="font-family: Courier New; background-color: #ffcc5c; color: #000000; padding: 3px; ">EG</span>

In [11]:
# Respuesta
#https://www.w3resource.com/pandas/series/series-value_counts.php

#Importamos librerias
import pandas as pd

#No hay contenedores con tamaños exactos de muestras en qLat y qLon, aunque son similares 
#me imagino que es porque hay valores de coordenadas duplicados y se tienen que atribuir a un "bin" o a otro
#Los intervalos son equidistantes entre segmentos para sLat y sLon
print("El número de muestras para qLat es:\n\n{}\n\n".format(housings.qLat.value_counts()))
print("El número de muestras para qLon es:\n\n{}\n\n".format(housings.qLon.value_counts()))
print("El número de muestras para sLat son:\n\n{}\n\n".format(housings.sLat.value_counts()))
print("El número de muestras para sLon son:\n\n{}".format(housings.sLon.value_counts()))

El número de muestras para qLat es:

(33.63, 33.87]     2160
(34.0, 34.1]       2138
(37.48, 37.81]     2112
(32.539, 33.63]    2092
(36.66, 37.48]     2073
(38.48, 41.95]     2061
(33.87, 34.0]      2058
(37.81, 38.48]     2005
(34.26, 36.66]     2000
(34.1, 34.26]      1941
Name: qLat, dtype: int64


El número de muestras para qLon es:

(-119.91, -118.49]     2106
(-122.29, -121.98]     2093
(-124.351, -122.29]    2075
(-118.13, -117.89]     2070
(-118.49, -118.3]      2066
(-121.37, -119.91]     2059
(-117.89, -117.25]     2054
(-117.25, -114.31]     2044
(-118.3, -118.13]      2043
(-121.98, -121.37]     2030
Name: qLon, dtype: int64


El número de muestras para sLat son:

(33.481, 34.422]    8987
(37.245, 38.186]    4712
(32.531, 33.481]    1796
(38.186, 39.127]    1740
(36.304, 37.245]    1292
(34.422, 35.363]     747
(39.127, 40.068]     490
(35.363, 36.304]     474
(40.068, 41.009]     324
(41.009, 41.95]       78
Name: sLat, dtype: int64


El número de muestras para sLon son:

(-118.326, -117.322]    6208
(-122.342, -121.338]    4564
(-119.33, -118.326]     2871
(-117.322, -116.318]    2252
(-121.338, -120.334]    1673
(-123.346, -122.342]    1553
(-120.334, -119.33]     1114
(-124.36, -123.346]      190
(-116.318, -115.314]     183
(-115.314, -114.31]       32
Name: sLon, dtype: int64

c) Muestra

- los precios promedio por cada segmento de Latitud (sLat)

- los precios promedio por cada segmento de Longitud (sLon)


**(1 punto)**  <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [14]:
# Respuesta
#https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html
#https://stackoverflow.com/questions/32751229/pandas-sum-by-groupby-but-exclude-certain-columns

#importamos librerias
import pandas as pd

#Agrupo
group = housings.groupby(['sLat','sLon'])

#Calculo las medias de los precios
print("Promedio de precios para (sLat,sLon):\n\n{}\n\n".format(group[['Prices']].mean().dropna()))

Promedio de precios para (sLat,sLon):

                                         Prices
sLat             sLon
(32.531, 33.481] (-119.33, -118.326]   3.511000
                 (-118.326, -117.322]  2.732589
                 (-117.322, -116.318]  1.965858
                 (-116.318, -115.314]  0.756287
                 (-115.314, -114.31]   0.478000
(33.481, 34.422] (-120.334, -119.33]   3.104987
                 (-119.33, -118.326]   3.034012
                 (-118.326, -117.322]  2.109366
                 (-117.322, -116.318]  1.271735
                 (-116.318, -115.314]  0.943333
                 (-115.314, -114.31]   0.787105
(34.422, 35.363] (-121.338, -120.334]  1.841825
                 (-120.334, -119.33]   3.077077
                 (-119.33, -118.326]   1.238817
                 (-118.326, -117.322]  1.319486
                 (-117.322, -116.318]  0.979061
                 (-116.318, -115.314]  0.841667
                 (-115.314, -114.31]   0.602143
(35.363, 36.304] (-122.342, -121.338]  3.198000
                 (-121.338, -120.334]  1.734746
                 (-120.334, -119.33]   0.744333
                 (-119.33, -118.326]   0.762546
                 (-118.326, -117.322]  0.833667
                 (-117.322, -116.318]  0.314500
                 (-116.318, -115.314]  0.502000
(36.304, 37.245] (-123.346, -122.342]  2.861000
                 (-122.342, -121.338]  2.664463
                 (-121.338, -120.334]  1.040304
                 (-120.334, -119.33]   0.845194
                 (-119.33, -118.326]   0.846614
                 (-118.326, -117.322]  0.983000
                 (-117.322, -116.318]  0.149990
(37.245, 38.186] (-123.346, -122.342]  3.268327
                 (-122.342, -121.338]  2.512896
                 (-121.338, -120.334]  1.173667
                 (-120.334, -119.33]   1.142060
                 (-119.33, -118.326]   1.451917
                 (-118.326, -117.322]  1.083000
(38.186, 39.127] (-124.36, -123.346]   1.595333
                 (-123.346, -122.342]  1.856552
                 (-122.342, -121.338]  1.334869
                 (-121.338, -120.334]  1.554368
                 (-120.334, -119.33]   1.327200
                 (-119.33, -118.326]   1.148000
(39.127, 40.068] (-124.36, -123.346]   1.254941
                 (-123.346, -122.342]  1.074340
                 (-122.342, -121.338]  0.851146
                 (-121.338, -120.334]  1.262206
                 (-120.334, -119.33]   1.498469
(40.068, 41.009] (-124.36, -123.346]   0.881215
                 (-123.346, -122.342]  0.860163
                 (-122.342, -121.338]  0.862488
                 (-121.338, -120.334]  0.905412
                 (-120.334, -119.33]   0.476000
(41.009, 41.95]  (-124.36, -123.346]   0.850897
                 (-123.346, -122.342]  0.717391
                 (-122.342, -121.338]  0.672625
                 (-121.338, -120.334]  0.509875
                 (-120.334, -119.33]   0.543500

d) Calcula y muestra la media y la desviación típica para todas las variables para cada combinación de Latitud y Longitud en ambos casos (equidensidad por segmento, equidistancia por segmento). 
Observación: quita las filas que contengan algún NaN del dataframe resultante. 

**(1 punto)**  <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [671]:
# Respuesta
#importamos librerias
import pandas as pd

#Agrupamos. La claúsula groupby excluye nans por defecto
sgroup = housings.groupby(['sLat','sLon'])
qgroup = housings.groupby(['qLat','qLon'])

#Hago print directamente
print("Medias para las combinaciones sLat,sLon:\n\n{}\n\n".format(sgroup.aggregate(np.mean).dropna()))
print("Desviaciones para las combinaciones sLat,sLon:\n\n{}\n\n".format(sgroup.aggregate(np.std).dropna()))
print("Medias para las combinaciones qLat,qLon:\n\n{}\n\n".format(qgroup.aggregate(np.mean).dropna()))
print("Desviaciones para las combinaciones qLat,qLon:\n\n{}".format(qgroup.aggregate(np.std).dropna()))

Medias para las combinaciones sLat,sLon:

                                         MedInc   HouseAge   AveRooms  \
sLat             sLon
(32.531, 33.481] (-119.33, -118.326]   2.718750  40.500000   4.806023
                 (-118.326, -117.322]  4.076581  20.578947   5.556501
                 (-117.322, -116.318]  3.808752  23.618345   5.294258
                 (-116.318, -115.314]  2.573830  22.382609   5.407458
                 (-115.314, -114.31]   1.375433  19.000000   5.010392
(33.481, 34.422] (-120.334, -119.33]   3.685874  30.371429   4.820485
                 (-119.33, -118.326]   4.704980  31.586966   5.184441
                 (-118.326, -117.322]  3.903039  30.708291   4.995189
                 (-117.322, -116.318]  3.197374  20.814145   6.850075
                 (-116.318, -115.314]  2.789075  19.063492   5.983722
                 (-115.314, -114.31]   2.089495  20.736842   9.765687
(34.422, 35.363] (-121.338, -120.334]  3.371835  21.663507   5.434861
                 (-120.334, -119.33]   4.406225  28.060606   5.643866
                 (-119.33, -118.326]   3.422266  22.310976   5.494059
                 (-118.326, -117.322]  3.561211  17.452703   5.761020
                 (-117.322, -116.318]  2.958672  17.560976   5.829443
                 (-116.318, -115.314]  2.444533   9.666667   5.620588
                 (-115.314, -114.31]   2.042643  30.428571   5.652171
(35.363, 36.304] (-122.342, -121.338]  2.966500  24.333333   5.530692
                 (-121.338, -120.334]  3.191172  19.447761   5.727988
                 (-120.334, -119.33]   2.426700  22.911111   5.142347
                 (-119.33, -118.326]   2.591696  27.578571   5.521692
                 (-118.326, -117.322]  3.812083  15.633333   5.855835
                 (-117.322, -116.318]  3.064150  21.500000   6.446385
                 (-116.318, -115.314]  2.274950  16.000000   6.143224
(36.304, 37.245] (-123.346, -122.342]  3.304700  52.000000   7.936364
                 (-122.342, -121.338]  4.399162  26.604331   5.679857
                 (-121.338, -120.334]  2.584193  23.803571   5.172068
                 (-120.334, -119.33]   2.921944  25.572100   5.454353
                 (-119.33, -118.326]   2.673786  23.879518   5.957268
                 (-118.326, -117.322]  2.219460  26.600000   5.560877
                 (-117.322, -116.318]  2.100000  19.000000   3.774390
(37.245, 38.186] (-123.346, -122.342]  4.315019  41.299278   5.064992
                 (-122.342, -121.338]  4.641461  31.190427   5.477858
                 (-121.338, -120.334]  2.929399  26.632812   5.274352
                 (-120.334, -119.33]   2.754187  18.567164   7.336428
                 (-119.33, -118.326]   3.344854  19.750000  12.423785
                 (-118.326, -117.322]  2.121200  16.000000   5.330532
(38.186, 39.127] (-124.36, -123.346]   2.887183  24.000000   7.855466
                 (-123.346, -122.342]  3.460444  24.483491   5.816354
                 (-122.342, -121.338]  3.302405  28.247537   5.374940
                 (-121.338, -120.334]  3.813198  18.312500   5.986351
                 (-120.334, -119.33]   2.951134  20.415385  18.281279
                 (-119.33, -118.326]   2.950900  19.000000  11.625874
(39.127, 40.068] (-124.36, -123.346]   2.566715  25.235294   5.395818
                 (-123.346, -122.342]  2.698684  24.860000   5.807399
                 (-122.342, -121.338]  2.383061  26.130769   5.390871
                 (-121.338, -120.334]  2.843559  21.030928   6.548406
                 (-120.334, -119.33]   3.463469  19.530612  16.302111
(40.068, 41.009] (-124.36, -123.346]   2.491731  31.842975   5.319756
                 (-123.346, -122.342]  2.359157  21.406977   5.718057
                 (-122.342, -121.338]  2.692041  20.097561   5.840844
                 (-121.338, -120.334]  2.795091  24.117647   9.476338
                 (-120.334, -119.33]   2.676500  26.000000   5.415350
(41.009, 41.95]  (-124.36, -123.346]   2.240110  21.000000   5.548015
                 (-123.346, -122.342]  2.347070  25.434783   5.889369
                 (-122.342, -121.338]  2.065131  30.937500   6.431523
                 (-121.338, -120.334]  2.332063  24.750000   6.609717
                 (-120.334, -119.33]   2.348250  33.500000   7.304939

                                       AveBedrms   Population   AveOccup  \
sLat             sLon
(32.531, 33.481] (-119.33, -118.326]    1.304112   761.000000   2.495755
                 (-118.326, -117.322]   1.136217  1640.184211   2.620678
                 (-117.322, -116.318]   1.061828  1501.449647   2.808020
                 (-116.318, -115.314]   1.186299   921.965217   3.307961
                 (-115.314, -114.31]    1.607271   636.666667   2.481195
(33.481, 34.422] (-120.334, -119.33]    1.085541  1113.800000   2.818824
                 (-119.33, -118.326]    1.051016  1486.561070   2.773664
                 (-118.326, -117.322]   1.048930  1545.472758   3.254030
                 (-117.322, -116.318]   1.365480  1686.703947   2.805449
                 (-116.318, -115.314]   1.398623  1776.936508   3.352446
                 (-115.314, -114.31]    2.181419  1031.000000   3.211153
(34.422, 35.363] (-121.338, -120.334]   1.066250  1371.829384   5.330034
                 (-120.334, -119.33]    1.078209  1129.371212   2.673001
                 (-119.33, -118.326]    1.083525  1996.670732   3.559465
                 (-118.326, -117.322]   1.110727  2115.506757   2.983479
                 (-117.322, -116.318]   1.160814  1716.060976   2.919417
                 (-116.318, -115.314]   1.456081  3839.000000   3.799755
                 (-115.314, -114.31]    1.234370   766.285714   2.541326
(35.363, 36.304] (-122.342, -121.338]   1.497352   429.666667   2.419213
                 (-121.338, -120.334]   1.160474  1529.283582   2.924583
                 (-120.334, -119.33]    1.063475  1097.344444   3.372457
                 (-119.33, -118.326]    1.154692  1223.925000   3.102350
                 (-118.326, -117.322]   1.150083  1263.033333   2.646701
                 (-117.322, -116.318]   1.221129  5133.000000   3.665733
                 (-116.318, -115.314]   1.507873   595.000000   2.691616
(36.304, 37.245] (-123.346, -122.342]   1.431818   941.000000   4.277273
                 (-122.342, -121.338]   1.088328  1547.891732   2.931609
                 (-121.338, -120.334]   1.092083  1217.071429   3.570460
                 (-120.334, -119.33]    1.068298  1262.009404   3.115483
                 (-119.33, -118.326]    1.240462  1245.855422   3.260897
                 (-118.326, -117.322]   1.211772   873.600000   2.363765
                 (-117.322, -116.318]   1.457317   490.000000   2.987805
(37.245, 38.186] (-123.346, -122.342]   1.058351  1305.754386   2.608468
                 (-122.342, -121.338]   1.044492  1345.787374   2.775978
                 (-121.338, -120.334]   1.064289  1197.945312   3.126795
                 (-120.334, -119.33]    1.529643   830.985075   2.685759
                 (-119.33, -118.326]    2.755048   791.333333   2.506460
                 (-118.326, -117.322]   1.112045  1501.000000   2.102241
(38.186, 39.127] (-124.36, -123.346]    1.576837   941.833333   2.528419
                 (-123.346, -122.342]   1.152071  1093.257075   2.603164
                 (-122.342, -121.338]   1.052883  1476.596059   4.258991
                 (-121.338, -120.334]   1.092825  1458.201389   3.265221
                 (-120.334, -119.33]    3.814038   543.600000   2.531466
                 (-119.33, -118.326]    2.307692   750.000000   2.622378
(39.127, 40.068] (-124.36, -123.346]    1.173370   987.117647   2.519219
                 (-123.346, -122.342]   1.223901   871.580000   2.733011
                 (-122.342, -121.338]   1.098238  1129.738462   2.677512
                 (-121.338, -120.334]   1.317870   825.463918   2.492622
                 (-120.334, -119.33]    3.016187   461.265306   2.523066
(40.068, 41.009] (-124.36, -123.346]    1.133961   914.181818   2.583794
                 (-123.346, -122.342]   1.202527  1059.186047   2.636571
                 (-122.342, -121.338]   1.177367  1178.914634   2.675585
                 (-121.338, -120.334]   2.009485   914.000000  20.102067
                 (-120.334, -119.33]    1.169300  1037.000000   2.340858
(41.009, 41.95]  (-124.36, -123.346]    1.203282  1181.758621   2.765369
                 (-123.346, -122.342]   1.204826  1135.695652   2.541386
                 (-122.342, -121.338]   1.352462  1168.750000   2.470046
                 (-121.338, -120.334]   1.286551  1174.125000   2.770776
                 (-120.334, -119.33]    1.374913   705.000000   2.430019

                                        Latitude   Longitude    Prices
sLat             sLon
(32.531, 33.481] (-119.33, -118.326]   33.385000 -118.405000  3.511000
                 (-118.326, -117.322]  33.329825 -117.531930  2.732589
                 (-117.322, -116.318]  32.845645 -117.109044  1.965858
                 (-116.318, -115.314]  32.902174 -115.608174  0.756287
                 (-115.314, -114.31]   32.931667 -114.700000  0.478000
(33.481, 34.422] (-120.334, -119.33]   34.401429 -119.680286  3.104987
                 (-119.33, -118.326]   34.107108 -118.521489  3.034012
                 (-118.326, -117.322]  33.934898 -118.016333  2.109366
                 (-117.322, -116.318]  33.977237 -117.047895  1.271735
                 (-116.318, -115.314]  33.796190 -116.169841  0.943333
                 (-115.314, -114.31]   33.718947 -114.627368  0.787105
(34.422, 35.363] (-121.338, -120.334]  34.986825 -120.533175  1.841825
                 (-120.334, -119.33]   34.555227 -119.789242  3.077077
                 (-119.33, -118.326]   35.090610 -118.912805  1.238817
                 (-118.326, -117.322]  34.687162 -117.997770  1.319486
                 (-117.322, -116.318]  34.639756 -117.145610  0.979061
                 (-116.318, -115.314]  34.863333 -115.806667  0.841667
                 (-115.314, -114.31]   34.800000 -114.662857  0.602143
(35.363, 36.304] (-122.342, -121.338]  36.183333 -121.616667  3.198000
                 (-121.338, -120.334]  35.705821 -120.754030  1.734746
                 (-120.334, -119.33]   36.075556 -119.580000  0.744333
                 (-119.33, -118.326]   35.725679 -119.045464  0.762546
                 (-118.326, -117.322]  35.646333 -117.752333  0.833667
                 (-117.322, -116.318]  35.485000 -116.930000  0.314500
                 (-116.318, -115.314]  35.775000 -116.075000  0.502000
(36.304, 37.245] (-123.346, -122.342]  37.180000 -122.380000  2.861000
                 (-122.342, -121.338]  36.904626 -121.832441  2.664463
                 (-121.338, -120.334]  36.859286 -120.802321  1.040304
                 (-120.334, -119.33]   36.717226 -119.748918  0.845194
                 (-119.33, -118.326]   36.441566 -119.227590  0.846614
                 (-118.326, -117.322]  36.866000 -118.148000  0.983000
                 (-117.322, -116.318]  36.400000 -117.020000  0.149990
(37.245, 38.186] (-123.346, -122.342]  37.779670 -122.455841  3.268327
                 (-122.342, -121.338]  37.646948 -122.062338  2.512896
                 (-121.338, -120.334]  37.755521 -121.019635  1.173667
                 (-120.334, -119.33]   37.696866 -120.039851  1.142060
                 (-119.33, -118.326]   37.546667 -118.762917  1.451917
                 (-118.326, -117.322]  37.350000 -118.180000  1.083000
(38.186, 39.127] (-124.36, -123.346]   38.888333 -123.508333  1.595333
                 (-123.346, -122.342]  38.527146 -122.715071  1.856552
                 (-122.342, -121.338]  38.549717 -121.629729  1.334869
                 (-121.338, -120.334]  38.677963 -121.102662  1.554368
                 (-120.334, -119.33]   38.845846 -120.013231  1.327200
                 (-119.33, -118.326]   38.260000 -119.300000  1.148000
(39.127, 40.068] (-124.36, -123.346]   39.487059 -123.661765  1.254941
                 (-123.346, -122.342]  39.282800 -123.079800  1.074340
                 (-122.342, -121.338]  39.541385 -121.743962  0.851146
                 (-121.338, -120.334]  39.385567 -120.989485  1.262206
                 (-120.334, -119.33]   39.317959 -120.144898  1.498469
(40.068, 41.009] (-124.36, -123.346]   40.718347 -124.065372  0.881215
                 (-123.346, -122.342]  40.563372 -122.552674  0.860163
                 (-122.342, -121.338]  40.464634 -122.164024  0.862488
                 (-121.338, -120.334]  40.366471 -120.804118  0.905412
                 (-120.334, -119.33]   40.260000 -120.200000  0.476000
(41.009, 41.95]  (-124.36, -123.346]   41.530000 -123.991034  0.850897
                 (-123.346, -122.342]  41.584348 -122.655217  0.717391
                 (-122.342, -121.338]  41.385000 -122.083125  0.672625
                 (-121.338, -120.334]  41.450000 -120.852500  0.509875
                 (-120.334, -119.33]   41.595000 -120.100000  0.543500


Desviaciones para las combinaciones sLat,sLon:

                                         MedInc   HouseAge   AveRooms  \
sLat             sLon
(32.531, 33.481] (-119.33, -118.326]   0.161998  16.263456   0.943697
                 (-118.326, -117.322]  1.685278   9.547177   1.215362
                 (-117.322, -116.318]  1.707274  11.558855   1.303187
                 (-116.318, -115.314]  1.244921   9.464229   1.328501
                 (-115.314, -114.31]   0.893500   3.162278   2.512852
(33.481, 34.422] (-120.334, -119.33]   1.892130  11.129243   1.743260
                 (-119.33, -118.326]   2.264984  10.858243   1.337319
                 (-118.326, -117.322]  1.866330  11.518467   1.301449
                 (-117.322, -116.318]  1.415454  12.279421   3.857749
                 (-116.318, -115.314]  1.305833   8.748959   3.030280
                 (-115.314, -114.31]   0.749694   5.733354  13.150795
(34.422, 35.363] (-121.338, -120.334]  1.226695  10.360895   1.085501
                 (-120.334, -119.33]   1.691543  10.351647   1.361800
                 (-119.33, -118.326]   1.812575  11.606836   1.032171
                 (-118.326, -117.322]  1.172127  12.064641   1.015738
                 (-117.322, -116.318]  1.130429  10.184832   1.035518
                 (-116.318, -115.314]  0.158798   4.041452   2.125042
                 (-115.314, -114.31]   0.565667  15.109127   0.515843
(35.363, 36.304] (-122.342, -121.338]  0.322781   4.041452   2.402658
                 (-121.338, -120.334]  0.849247   9.210145   1.119265
                 (-120.334, -119.33]   0.923033   9.119241   0.871112
                 (-119.33, -118.326]   1.188151  11.047352   2.439073
                 (-118.326, -117.322]  1.425991   8.231493   0.689721
                 (-117.322, -116.318]  0.495470  19.091883   0.686618
                 (-116.318, -115.314]  1.595021   2.828427   0.421564
(36.304, 37.245] (-122.342, -121.338]  1.914867  11.179323   1.634363
                 (-121.338, -120.334]  0.847390   9.443458   1.233131
                 (-120.334, -119.33]   1.344402  12.048840   2.177451
                 (-119.33, -118.326]   1.290918  10.010236   3.920579
                 (-118.326, -117.322]  0.376886   7.368853   0.946970
(37.245, 38.186] (-123.346, -122.342]  1.942132  11.944742   1.187590
                 (-122.342, -121.338]  2.120154  13.161049   1.298729
                 (-121.338, -120.334]  1.147449  12.508795   1.121625
                 (-120.334, -119.33]   0.734838   9.560373   3.864903
                 (-119.33, -118.326]   0.887974   8.435175  11.460306
(38.186, 39.127] (-124.36, -123.346]   0.471428  11.454257   4.390768
                 (-123.346, -122.342]  1.215403  11.079114   1.237592
                 (-122.342, -121.338]  1.407061  12.790894   1.072144
                 (-121.338, -120.334]  1.292358   8.626944   1.133084
                 (-120.334, -119.33]   0.919371   5.711535  25.044834
(39.127, 40.068] (-124.36, -123.346]   0.590332  11.292419   0.795565
                 (-123.346, -122.342]  1.014960   9.818787   2.499070
                 (-122.342, -121.338]  0.778531  11.283903   1.785101
                 (-121.338, -120.334]  0.857173  12.692233   3.285044
                 (-120.334, -119.33]   1.152259   9.083185  10.975562
(40.068, 41.009] (-124.36, -123.346]   0.837473  11.385670   0.969772
                 (-123.346, -122.342]  0.840736   8.634238   1.566729
                 (-122.342, -121.338]  0.876785   8.499252   2.079584
                 (-121.338, -120.334]  1.027794  11.475309   9.976913
(41.009, 41.95]  (-124.36, -123.346]   0.551748   4.942527   0.608168
                 (-123.346, -122.342]  0.657256   9.628679   0.942687
                 (-122.342, -121.338]  0.512585  12.347571   1.834141
                 (-121.338, -120.334]  0.247155   7.977647   0.689809
                 (-120.334, -119.33]   0.364796   0.707107   0.434758

                                       AveBedrms   Population    AveOccup  \
sLat             sLon
(32.531, 33.481] (-119.33, -118.326]    0.094919   479.418398    0.079831
                 (-118.326, -117.322]   0.171573  3350.622704    0.697800
                 (-117.322, -116.318]   0.128477  1128.605704    0.846740
                 (-116.318, -115.314]   0.304764   603.990617    1.138119
                 (-115.314, -114.31]    0.645197   512.332184    0.535102
(33.481, 34.422] (-120.334, -119.33]    0.141220   748.016190    0.963692
                 (-119.33, -118.326]    0.083795  1145.274211    1.171996
                 (-118.326, -117.322]   0.089159  1089.260216    1.279676
                 (-117.322, -116.318]   0.782282  1522.337957    0.635162
                 (-116.318, -115.314]   0.615614  1483.594468    0.926222
                 (-115.314, -114.31]    2.994187  1016.422102    2.259800
(34.422, 35.363] (-121.338, -120.334]   0.093089  1021.466392   34.413854
                 (-120.334, -119.33]    0.109533   473.532146    0.679352
                 (-119.33, -118.326]    0.150786  1839.475649    6.290260
                 (-118.326, -117.322]   0.127893  1996.107752    0.550056
                 (-117.322, -116.318]   0.244612  1060.236723    0.615258
                 (-116.318, -115.314]   0.466512  6322.242403    2.451526
                 (-115.314, -114.31]    0.234371   437.615400    0.299268
(35.363, 36.304] (-122.342, -121.338]   0.362115   151.862877    0.625971
                 (-121.338, -120.334]   0.197060   914.509967    1.108024
                 (-120.334, -119.33]    0.115247   579.698549    0.700107
                 (-119.33, -118.326]    0.628906   657.282287    0.847143
                 (-118.326, -117.322]   0.199440   539.754381    0.427188
                 (-117.322, -116.318]   0.013960  2406.991483    1.533139
                 (-116.318, -115.314]   0.430392   224.859956    0.911697
(36.304, 37.245] (-122.342, -121.338]   0.214547  1696.918995    0.833796
                 (-121.338, -120.334]   0.180711   723.500477    0.709412
                 (-120.334, -119.33]    0.388870   764.379366    0.833583
                 (-119.33, -118.326]    0.827735   499.600356    0.742421
                 (-118.326, -117.322]   0.143810   534.765182    0.199569
(37.245, 38.186] (-123.346, -122.342]   0.107707   844.955780    0.833250
                 (-122.342, -121.338]   0.097171  1005.856666    0.751094
                 (-121.338, -120.334]   0.138291   909.388484    2.085239
                 (-120.334, -119.33]    0.968811   527.139579    0.465262
                 (-119.33, -118.326]    2.509188   435.768852    0.277883
(38.186, 39.127] (-124.36, -123.346]    0.784706   450.450626    0.500804
                 (-123.346, -122.342]   0.253846   663.990303    0.569154
                 (-122.342, -121.338]   0.098024  1433.707054   43.542152
                 (-121.338, -120.334]   0.198102  1066.056673   10.971924
                 (-120.334, -119.33]    5.398766   319.437484    0.336468

Medias para las combinaciones qLat,qLon:

                                       MedInc   HouseAge   AveRooms  \
qLat            qLon
(32.539, 33.63] (-118.49, -118.3]    2.744420  42.400000   5.656577
                (-118.13, -117.89]   5.882535  30.557692   5.920610
                (-117.89, -117.25]   5.039886  18.984252   5.886267
                (-117.25, -114.31]   3.596781  23.563851   5.278766
(33.63, 33.87]  (-118.49, -118.3]    5.469732  30.471545   5.411688
                (-118.3, -118.13]    3.403173  34.924812   4.436297
                (-118.13, -117.89]   4.494720  26.284382   5.281510
                (-117.89, -117.25]   5.110573  19.108932   5.729497
                (-117.25, -114.31]   3.076170  15.777778   6.851792
(33.87, 34.0]   (-119.91, -118.49]   3.750171  38.000000   3.657667
                (-118.49, -118.3]    4.016103  36.275797   4.843512
                (-118.3, -118.13]    2.485158  36.111773   4.223250
                (-118.13, -117.89]   4.396109  31.173824   5.333785
                (-117.89, -117.25]   4.325288  23.413194   5.834526
                (-117.25, -114.31]   2.945431  17.142857   6.853007
(34.0, 34.1]    (-119.91, -118.49]   7.593832  33.323077   6.136858
                (-118.49, -118.3]    3.937410  38.338485   4.531700
                (-118.3, -118.13]    2.444141  38.064516   3.676160
                (-118.13, -117.89]   3.575224  32.117347   4.825734
                (-117.89, -117.25]   3.447544  25.809524   5.218920
                (-117.25, -114.31]   3.861184  22.551724   5.986773
(34.1, 34.26]   (-119.91, -118.49]   5.148549  25.082988   5.818360
                (-118.49, -118.3]    4.080295  32.691849   4.809535
                (-118.3, -118.13]    4.283538  37.904255   4.931651
                (-118.13, -117.89]   4.865886  37.328889   5.666465
                (-117.89, -117.25]   3.874902  26.263941   5.900387
                (-117.25, -114.31]   3.231963  18.988372  10.075050
(34.26, 36.66]  (-121.98, -121.37]   3.981567  30.827586   5.497438
                (-121.37, -119.91]   3.307965  20.988201   5.501812
                (-119.91, -118.49]   3.353408  26.359319   5.442527
                (-118.49, -118.3]    3.745757  26.264463   5.206721
                (-118.3, -118.13]    3.843348  20.855072   5.836368
                (-118.13, -117.89]   3.504453  16.075472   5.881179
                (-117.89, -117.25]   3.342948  14.336364   5.819976
                (-117.25, -114.31]   2.908234  19.736842   7.301825
(36.66, 37.48]  (-124.351, -122.29]  6.820343  31.428571   6.831308
                (-122.29, -121.98]   5.790986  30.359606   5.653640
                (-121.98, -121.37]   4.589755  25.220681   5.421622
                (-121.37, -119.91]   2.655521  24.375000   5.275709
                (-119.91, -118.49]   3.091592  24.951456   5.754875
                (-118.49, -118.3]    2.889590  25.800000   5.399943
                (-118.3, -118.13]    2.121200  16.000000   5.330532
                (-118.13, -117.89]   1.729200  19.000000   4.500000
(37.48, 37.81]  (-124.351, -122.29]  4.224052  43.025611   4.988860
                (-122.29, -121.98]   3.783957  35.334254   5.121494
                (-121.98, -121.37]   5.412914  21.352941   6.271525
                (-121.37, -119.91]   3.016095  25.194118   5.390533
                (-119.91, -118.49]   3.447611  16.944444  14.620639
                (-118.49, -118.3]    2.350000  15.000000   6.337176
(37.81, 38.48]  (-124.351, -122.29]  4.056617  30.296131   5.459806
                (-122.29, -121.98]   4.524556  32.976994   5.747651
                (-121.98, -121.37]   4.179612  20.972222   5.888638
                (-121.37, -119.91]   3.080600  25.376623   5.906045
                (-119.91, -118.49]   3.327967  17.000000  11.585095
(38.48, 41.95]  (-124.351, -122.29]  2.605523  24.882682   5.772042
                (-122.29, -121.98]   2.655656  25.648148   5.479712
                (-121.98, -121.37]   2.738421  29.823129   5.274807
                (-121.37, -119.91]   3.571912  19.731563   7.888790
                (-119.91, -118.49]   2.127233  17.000000   7.168680

                                     AveBedrms   Population  AveOccup  \
qLat            qLon
(32.539, 33.63] (-118.49, -118.3]     1.522004   668.000000  2.383127
                (-118.13, -117.89]    1.155927   809.500000  2.197507
                (-117.89, -117.25]    1.095260  1452.797244  2.557328
                (-117.25, -114.31]    1.073915  1478.599214  2.893769
(33.63, 33.87]  (-118.49, -118.3]     1.040746  1454.646341  2.613470
                (-118.3, -118.13]     1.061377  1468.629073  2.934585
                (-118.13, -117.89]    1.039861  1496.268065  3.085429
                (-117.89, -117.25]    1.051150  1672.435730  3.164086
                (-117.25, -114.31]    1.411602  1839.237374  2.728154
(33.87, 34.0]   (-119.91, -118.49]    1.097859   964.000000  1.561999
                (-118.49, -118.3]     1.056857  1226.874296  2.781540
                (-118.3, -118.13]     1.042103  1465.982116  3.865730
                (-118.13, -117.89]    1.029572  1346.036810  3.224068
                (-117.89, -117.25]    1.050617  2028.298611  3.481347
                (-117.25, -114.31]    1.398523  2210.057143  2.866828
(34.0, 34.1]    (-119.91, -118.49]    1.082245  1262.169231  2.400254
                (-118.49, -118.3]     1.063104  1364.564142  2.551028
                (-118.3, -118.13]     1.059079  1581.721063  3.764781
                (-118.13, -117.89]    1.028763  1694.494898  3.630439
                (-117.89, -117.25]    1.056004  1889.630952  3.372020
                (-117.25, -114.31]    1.090105  1426.206897  2.744893
(34.1, 34.26]   (-119.91, -118.49]    1.041367  1897.813278  3.035626
                (-118.49, -118.3]     1.051370  1448.998012  2.757283
                (-118.3, -118.13]     1.047665  1338.816489  2.791721
                (-118.13, -117.89]    1.050436  1257.093333  2.936150
                (-117.89, -117.25]    1.087435  1770.542751  3.104692
                (-117.25, -114.31]    2.132111  1212.116279  2.665826
(34.26, 36.66]  (-121.98, -121.37]    1.122736  1349.991379  2.510306
                (-121.37, -119.91]    1.094689  1388.545723  4.533711
                (-119.91, -118.49]    1.081791  1349.530466  3.163927
                (-118.49, -118.3]     1.097772  1889.760331  3.600766
                (-118.3, -118.13]     1.096783  1726.333333  2.900702
                (-118.13, -117.89]    1.133149  2304.150943  3.064584
                (-117.89, -117.25]    1.125644  1893.590909  2.908594
                (-117.25, -114.31]    1.493648  1596.065789  2.865787
(36.66, 37.48]  (-124.351, -122.29]   1.167245  1682.000000  2.746011
                (-122.29, -121.98]    1.046126  1222.315271  2.675765
                (-121.98, -121.37]    1.048196  1661.184111  3.151461
                (-121.37, -119.91]    1.068344  1247.187500  3.292621
                (-119.91, -118.49]    1.126388  1310.067961  2.943195
                (-118.49, -118.3]     1.086119  1212.200000  2.496066
                (-118.3, -118.13]     1.112045  1501.000000  2.102241
                (-118.13, -117.89]    1.181818    51.000000  2.318182
(37.48, 37.81]  (-124.351, -122.29]   1.058062  1286.370198  2.633853
                (-122.29, -121.98]    1.048251  1247.109116  2.783999
                (-121.98, -121.37]    1.055701  1726.241176  2.824960
                (-121.37, -119.91]    1.069155  1225.429412  3.056550
                (-119.91, -118.49]    3.272231   573.555556  2.524711
                (-118.49, -118.3]     1.305476   899.000000  2.590778
(37.81, 38.48]  (-124.351, -122.29]   1.060036  1216.794643  2.555806
                (-122.29, -121.98]    1.047693  1312.975460  4.500396
                (-121.98, -121.37]    1.060442  1741.203704  2.993574
                (-121.37, -119.91]    1.182559  1101.954545  3.046026
                (-119.91, -118.49]    3.479035   406.666667  2.545695
(38.48, 41.95]  (-124.351, -122.29]   1.212923   984.945996  2.624755
                (-122.29, -121.98]    1.079215  1037.787037  2.727878
                (-121.98, -121.37]    1.083922  1289.817687  2.675110
                (-121.37, -119.91]    1.508216  1253.162242  3.846054
                (-119.91, -118.49]    1.535800   580.333333  2.601016

                                      Latitude   Longitude    Prices
qLat            qLon
(32.539, 33.63] (-118.49, -118.3]    33.358000 -118.354000  3.804400
                (-118.13, -117.89]   33.616923 -117.919038  4.287755
                (-117.89, -117.25]   33.306988 -117.497106  2.949287
                (-117.25, -114.31]   32.848029 -116.940753  1.735214
(33.63, 33.87]  (-118.49, -118.3]    33.815000 -118.347846  3.558457
                (-118.3, -118.13]    33.804912 -118.198922  2.119712
                (-118.13, -117.89]   33.776620 -117.988065  2.310138
                (-117.89, -117.25]   33.751961 -117.763878  2.454210
                (-117.25, -114.31]   33.751414 -116.650253  1.353934
(33.87, 34.0]   (-119.91, -118.49]   33.985714 -118.508571  4.678579
                (-118.49, -118.3]    33.947129 -118.365422  2.576102
                (-118.3, -118.13]    33.941744 -118.221013  1.351019
                (-118.13, -117.89]   33.933108 -118.027035  2.130618
                (-117.89, -117.25]   33.936597 -117.550104  1.759021
                (-117.25, -114.31]   33.939571 -116.816286  1.057314
(34.0, 34.1]    (-119.91, -118.49]   34.044462 -118.562769  4.757300
                (-118.49, -118.3]    34.050804 -118.373338  3.258809
                (-118.3, -118.13]    34.054004 -118.217192  1.736531
                (-118.13, -117.89]   34.063342 -118.011684  1.896092
                (-117.89, -117.25]   34.065310 -117.594333  1.411510
                (-117.25, -114.31]   34.052644 -117.087241  1.428920
(34.1, 34.26]   (-119.91, -118.49]   34.200311 -118.771971  2.785644
                (-118.49, -118.3]    34.188608 -118.394394  2.667681
                (-118.3, -118.13]    34.159362 -118.211144  2.718129
                (-118.13, -117.89]   34.139244 -118.033733  2.913930
                (-117.89, -117.25]   34.137361 -117.489554  1.557829
                (-117.25, -114.31]   34.173953 -116.831163  1.082186
(34.26, 36.66]  (-121.98, -121.37]   36.573793 -121.825345  2.744475
                (-121.37, -119.91]   35.239381 -120.536313  1.817870
                (-119.91, -118.49]   35.384194 -119.241944  1.520766
                (-118.49, -118.3]    34.485289 -118.428099  1.694670
                (-118.3, -118.13]    34.726232 -118.178696  1.489043
                (-118.13, -117.89]   34.737736 -118.046226  1.281528
                (-117.89, -117.25]   34.827000 -117.475455  1.047345
                (-117.25, -114.31]   34.726053 -116.718158  0.903289
(36.66, 37.48]  (-124.351, -122.29]  37.384286 -122.348571  4.423863
                (-122.29, -121.98]   37.312660 -122.080230  3.518534
                (-121.98, -121.37]   37.208865 -121.833834  2.519614
                (-121.37, -119.91]   37.164708 -120.513292  0.929700
                (-119.91, -118.49]   36.813908 -119.735291  0.896376
                (-118.49, -118.3]    37.293000 -118.396000  1.130200
                (-118.3, -118.13]    37.350000 -118.180000  1.083000
                (-118.13, -117.89]   36.950000 -117.900000  1.375000
(37.48, 37.81]  (-124.351, -122.29]  37.710664 -122.424715  3.317813
                (-122.29, -121.98]   37.698812 -122.155331  2.040358
                (-121.98, -121.37]   37.679235 -121.792118  2.608471
                (-121.37, -119.91]   37.662294 -120.960971  1.309185
                (-119.91, -118.49]   37.640000 -119.235556  1.515667
                (-118.49, -118.3]    37.700000 -118.450000  1.078000
(37.81, 38.48]  (-124.351, -122.29]  38.146458 -122.525565  2.304526
                (-122.29, -121.98]   37.993512 -122.152178  2.281249
                (-121.98, -121.37]   38.121759 -121.776204  1.604199
                (-121.37, -119.91]   38.055541 -121.082749  1.177582
                (-119.91, -118.49]   38.076667 -119.283333  1.116000
(38.48, 41.95]  (-124.351, -122.29]  39.993091 -123.150894  1.074616
                (-122.29, -121.98]   39.847130 -122.164722  0.841926
                (-121.98, -121.37]   38.942490 -121.545347  1.089929
                (-121.37, -119.91]   39.002375 -120.949779  1.459195
                (-119.91, -118.49]   38.576667 -119.586667  1.037000


Desviaciones para las combinaciones qLat,qLon:

                                       MedInc   HouseAge   AveRooms  \
qLat            qLon
(32.539, 33.63] (-118.49, -118.3]    0.444180  13.164346   1.225239
                (-118.13, -117.89]   2.362263   8.564435   1.308915
                (-117.89, -117.25]   2.312767  10.274715   1.427208
                (-117.25, -114.31]   1.637609  11.482094   1.295490
(33.63, 33.87]  (-118.49, -118.3]    2.003316   8.771312   1.069302
                (-118.3, -118.13]    1.212555  10.009260   0.954655
                (-118.13, -117.89]   1.490364   8.139149   1.102027
                (-117.89, -117.25]   2.142979  10.166362   1.464021
                (-117.25, -114.31]   1.322040   7.764367   3.223026
(33.87, 34.0]   (-119.91, -118.49]   2.090202  11.328430   1.315505
                (-118.49, -118.3]    1.601272   9.433230   1.094115
                (-118.3, -118.13]    0.947699   7.248532   0.753336
                (-118.13, -117.89]   1.483095   8.076254   0.972994
                (-117.89, -117.25]   1.809000  11.308754   1.277424
                (-117.25, -114.31]   1.255333  10.069736   7.028121
(34.0, 34.1]    (-119.91, -118.49]   3.684406  10.628834   1.716578
                (-118.49, -118.3]    2.753832  10.339056   1.436192
                (-118.3, -118.13]    0.989802   9.832804   0.935036
                (-118.13, -117.89]   1.012486   6.912793   0.837166
                (-117.89, -117.25]   1.358013  12.313406   0.942582
                (-117.25, -114.31]   1.805478  12.084738   1.367513
(34.1, 34.26]   (-119.91, -118.49]   1.985111   8.939236   1.357830
                (-118.49, -118.3]    1.777639   9.880686   1.029697
                (-118.3, -118.13]    2.202202  11.429384   1.271498
                (-118.13, -117.89]   2.427514   9.403092   1.223806
                (-117.89, -117.25]   1.739377  12.121626   1.526758
                (-117.25, -114.31]   1.510721   8.134884   6.914097
(34.26, 36.66]  (-121.98, -121.37]   1.810332  10.870203   1.492340
                (-121.37, -119.91]   1.185521   9.769224   1.116802
                (-119.91, -118.49]   1.700751  10.934166   1.617694
                (-118.49, -118.3]    1.401547  10.384097   1.762789
                (-118.3, -118.13]    1.344373  11.590152   1.019067
                (-118.13, -117.89]   1.022524  12.359750   0.780821
                (-117.89, -117.25]   1.198867   9.428901   1.189912
                (-117.25, -114.31]   1.172693  10.567079   4.482932
(36.66, 37.48]  (-124.351, -122.29]  2.355830  15.479633   0.796553
                (-122.29, -121.98]   2.532643   9.564897   1.390159
                (-121.98, -121.37]   1.699340  11.340371   1.476575
                (-121.37, -119.91]   0.961472  10.545032   0.941242
                (-119.91, -118.49]   1.515667  13.175683   3.248683
                (-118.49, -118.3]    1.048031   7.299924   0.888376
(37.48, 37.81]  (-124.351, -122.29]  1.857259  11.071680   1.166137
                (-122.29, -121.98]   1.545953  12.673968   1.049324
                (-121.98, -121.37]   2.082735  11.876789   1.772748
                (-121.37, -119.91]   1.184719  11.904634   1.293495
                (-119.91, -118.49]   0.639684   5.915804  12.071009
(37.81, 38.48]  (-124.351, -122.29]  1.694273  12.329074   1.125042
                (-122.29, -121.98]   2.159951  14.480171   1.305264
                (-121.98, -121.37]   1.852073  12.757457   1.120530
                (-121.37, -119.91]   1.171517  12.948628   3.550871
                (-119.91, -118.49]   0.327961   2.000000   5.735403
(38.48, 41.95]  (-124.351, -122.29]  0.938676  10.765444   1.466599
                (-122.29, -121.98]   0.808486  10.573565   0.623567
                (-121.98, -121.37]   1.155947  12.252065   1.518754
                (-121.37, -119.91]   1.306140   9.570167   9.348502
                (-119.91, -118.49]   0.475084   3.000000   1.816000

                                     AveBedrms   Population   AveOccup  \
qLat            qLon
(32.539, 33.63] (-118.49, -118.3]     0.217067   301.691067   0.186925
                (-118.13, -117.89]    0.160483   405.205903   0.355265
                (-117.89, -117.25]    0.137718  1881.532638   0.662883
                (-117.25, -114.31]    0.164264  1157.916668   0.921515
(33.63, 33.87]  (-118.49, -118.3]     0.061367  1069.124433   0.454958
                (-118.3, -118.13]     0.085110   904.928295   0.867525
                (-118.13, -117.89]    0.084930   855.634216   0.863522
                (-117.89, -117.25]    0.097920  1215.185824   0.964295
                (-117.25, -114.31]    0.636110  1277.622462   0.818312
(33.87, 34.0]   (-119.91, -118.49]    0.050691   365.778622   0.336573
                (-118.49, -118.3]     0.088491   904.150817   0.661933
                (-118.3, -118.13]     0.081132   820.527664   0.722817
                (-118.13, -117.89]    0.063652   901.690784   0.722742
                (-117.89, -117.25]    0.100242  1979.983599   4.053056
                (-117.25, -114.31]    1.574651  2242.622132   0.679736
(34.0, 34.1]    (-119.91, -118.49]    0.123084   909.965394   0.698014
                (-118.49, -118.3]     0.080267   877.065865   1.656751
                (-118.3, -118.13]     0.092509   915.903554   1.263653
                (-118.13, -117.89]    0.066584  1137.204431   0.721388
                (-117.89, -117.25]    0.095299  1627.314199   1.202019
                (-117.25, -114.31]    0.226170   719.267750   0.539470
(34.1, 34.26]   (-119.91, -118.49]    0.085074  1474.939415   1.040308
                (-118.49, -118.3]     0.075674  1013.210596   0.812410
                (-118.3, -118.13]     0.067199   811.244733   0.592450
                (-118.13, -117.89]    0.088969   752.118327   0.731706
                (-117.89, -117.25]    0.218129  1427.332943   0.606733
                (-117.25, -114.31]    1.471083   976.669592   0.388910
(34.26, 36.66]  (-121.98, -121.37]    0.159847  2659.143610   0.642251
                (-121.37, -119.91]    0.136272  1017.818470  27.153379
                (-119.91, -118.49]    0.322030   954.565583   2.535808
                (-118.49, -118.3]     0.408895  1683.492303   1.110337
                (-118.3, -118.13]     0.089985  1476.194608   0.586149
                (-118.13, -117.89]    0.138404  2416.293286   0.557475
                (-117.89, -117.25]    0.172376  1364.610811   0.628511
                (-117.25, -114.31]    0.822529  1643.809813   0.583360
(36.66, 37.48]  (-124.351, -122.29]   0.142659  1833.465935   0.709283
                (-122.29, -121.98]    0.107480   846.316226   0.766041
                (-121.98, -121.37]    0.167226  1208.527916   0.868281
                (-121.37, -119.91]    0.140677   733.682460   0.622998
                (-119.91, -118.49]    0.645795   800.047459   0.630579
                (-118.49, -118.3]     0.128455   289.888024   0.365466
(37.48, 37.81]  (-124.351, -122.29]   0.104052   775.363679   0.862077
                (-122.29, -121.98]    0.111376   975.883089   0.723857
                (-121.98, -121.37]    0.129231  1554.186876   0.426041
                (-121.37, -119.91]    0.161308  1028.526224   1.439324
                (-119.91, -118.49]    2.603936   385.337930   0.322575
(37.81, 38.48]  (-124.351, -122.29]   0.129512   807.898803   0.491988
                (-122.29, -121.98]    0.088378  1010.012054  48.595829

## Ejercicio 4

### Estandarización de variables.

Importa el dataset `iris` de `sklearn`. Almacena este dataset como un objeto `pandas`, con los correpondientres nombres de variables. 

Llamamos tipificar una variable al proceso de convertirla en una Normal Estándar $N(\mu=0,\sigma =1)$.
Busca en `sklearn.preprocessing` un método que te permita tipificar cada variable numérica del objeto pandas de `iris` de forma que:

- El valor medio de cada columna sea 0
- La desviación típica de cada columna sea 1

a) Aplica el método para crear un nuevo dataframne `iris_typ` que cumpla esas condiciones.  Comprueba que la tipificación es correcta.

**(1 punto)** <span style="font-family: Courier New; background-color: #ffcc5c; color: #000000; padding: 3px; ">EG</span>

In [3]:
# Respuesta
#El StandardScaler está en el material también

#Importamos librerias
import pandas as pd
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

#Cargamos el dataframe
iris_bunch = datasets.load_iris()
#print(iris_bunch.keys())
dfiris = pd.DataFrame(iris_bunch.data, columns=iris_bunch.feature_names)
dfiris['Species'] = iris_bunch["target_names"][iris_bunch["target"]]
print("Las estadísticas iniciales son:\n\n{}\n\n".format(dfiris.describe()))

#Hago copia del dataframe :) y uso el StandardScaler
iris_typ = dfiris.copy()
iris_typ.loc[:, ["sepal length (cm)","sepal width (cm)", "petal length (cm)", 
                 "petal width (cm)"]] = StandardScaler().fit_transform(dfiris.loc[:, ["sepal length (cm)",
                                                                                      "sepal width (cm)", 
                                                                                      "petal length (cm)", 
                                                                                    "petal width (cm)"]])
#La media tiende a 0 (-1.46 x10⁻15) y la desviación tiende a 1
print("Las estadísticas finales son:\n\n{}".format(iris_typ.describe()))

Las estadísticas iniciales son:

       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000
mean            5.843333          3.057333           3.758000
std             0.828066          0.435866           1.765298
min             4.300000          2.000000           1.000000
25%             5.100000          2.800000           1.600000
50%             5.800000          3.000000           4.350000
75%             6.400000          3.300000           5.100000
max             7.900000          4.400000           6.900000

       petal width (cm)
count        150.000000
mean           1.199333
std            0.762238
min            0.100000
25%            0.300000
50%            1.300000
75%            1.800000
max            2.500000


Las estadísticas finales son:

       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count       1.500000e+02      1.500000e+02       1.500000e+02
mean       -1.468455e-15     -1.823726e-15      -1.610564e-15
std         1.003350e+00      1.003350e+00       1.003350e+00
min        -1.870024e+00     -2.433947e+00      -1.567576e+00
25%        -9.006812e-01     -5.923730e-01      -1.226552e+00
50%        -5.250608e-02     -1.319795e-01       3.364776e-01
75%         6.745011e-01      5.586108e-01       7.627583e-01
max         2.492019e+00      3.090775e+00       1.785832e+00

       petal width (cm)
count      1.500000e+02
mean      -9.000208e-16
std        1.003350e+00
min       -1.447076e+00
25%       -1.183812e+00
50%        1.325097e-01
75%        7.906707e-01
max        1.712096e+00

b) Busca y aplica un segundo mecanismo de normalización de forma que:

- el mínimo de la variable sea 0, y 
- el máximo de cada variable sea 1 

Comprueba que la normalizacion es correcta

**(0.5 puntos)** <span style="font-family: Courier New; background-color: #ffcc5c; color: #000000; padding: 3px; ">EG</span>

In [673]:
# Respuesta

#Importamos librerias
import pandas as pd
import sklearn as sk
from sklearn.preprocessing import MinMaxScaler

#Para cada atributo calcula la diferencia entre un valor y el mín. y divide entre la diferencia entre el max. y el min.
#Hago copia del dataframe y uso el MinMaxScaler
iris_typ2 = dfiris.copy()
iris_typ2.loc[:, ["sepal length (cm)","sepal width (cm)", "petal length (cm)", 
                 "petal width (cm)"]] = MinMaxScaler().fit_transform(dfiris.loc[:, ["sepal length (cm)",
                                                                                      "sepal width (cm)", 
                                                                                      "petal length (cm)", 
                                                                                    "petal width (cm)"]])


print("Las estadísticas iniciales son:\n\n{}\n\n".format(dfiris.describe()))
#Vemos que el mínimo es 0 y el mínimo 1
print("Las estadísticas finales son:\n\n{}".format(iris_typ2.describe()))

Las estadísticas iniciales son:

       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000
mean            5.843333          3.057333           3.758000
std             0.828066          0.435866           1.765298
min             4.300000          2.000000           1.000000
25%             5.100000          2.800000           1.600000
50%             5.800000          3.000000           4.350000
75%             6.400000          3.300000           5.100000
max             7.900000          4.400000           6.900000

       petal width (cm)
count        150.000000
mean           1.199333
std            0.762238
min            0.100000
25%            0.300000
50%            1.300000
75%            1.800000
max            2.500000


Las estadísticas finales son:

       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000
mean            0.428704          0.440556           0.467458
std             0.230018          0.181611           0.299203
min             0.000000          0.000000           0.000000
25%             0.222222          0.333333           0.101695
50%             0.416667          0.416667           0.567797
75%             0.583333          0.541667           0.694915
max             1.000000          1.000000           1.000000

       petal width (cm)
count        150.000000
mean           0.458056
std            0.317599
min            0.000000
25%            0.083333
50%            0.500000
75%            0.708333
max            1.000000

### Ejercicio Opcional


La Oficina de Estadísticas de Transporte del Departamento de Transporte de los Estados Unidos (DOT) rastrea el rendimiento en término de puntualidad de los vuelos en EE.UU. operados por grandes compañías aéreas. 

La información resumida sobre el número de vuelos puntuales, retrasados, cancelados y desviados se publica en el Informe mensual del consumidor de viajes aéreos del DOT y en este conjunto de datos de retrasos y cancelaciones de vuelos de 2015. Encontrarás una muestra de estos datos en el fichero `vuelos.csv` en la carpeta de datos. 

Importa el fichero de vuelos. Imputa los valores perdidos con el método KNNImputer con los valores por defecto.

Calcula y muestra la matriz de correlación de las siguientes variables a partir de la matriz imputada. 

- `ARRIVAL_DELAY`
- `DIVERTED`
- `CANCELLED`	
- `AIR_SYSTEM_DELAY`
- `SECURITY_DELAY`
- `AIRLINE_DELAY`
- `LATE_AIRCRAFT_DELAY`
- `WEATHER_DELAY`

Interpreta el resultado


 <span style="font-family: Courier New; background-color: #f2ae72; color: #000000; padding: 3px; ">EI</span>

In [674]:
# Respuesta
#https://stackoverflow.com/questions/36518027/pandas-creating-new-data-frame-from-only-certain-columns

#Importamos librerias
import pandas as pd
from sklearn.impute import SimpleImputer

#Decimal tiene que ser "," para que SimpleImputer pueda hacer la media de los valores
df = pd.read_csv("data/vuelos.csv", sep=";", decimal=',')

# Sustituiremos los valores perdidos por la media de la columna 
imp = SimpleImputer(strategy='mean')
#print(df.head())

#Identificamos manualmente qué tipo de datos hay en las columnas que nos interesan, con head() o tail()
#No hay que binarizar ninguna, ya que no hay columnas con valores categóricos
#print(df.tail())

#Sustituyo los NaNs
df["ARRIVAL_DELAY"]= imp.fit_transform(df[["ARRIVAL_DELAY"]]).ravel().round(1)
df["DIVERTED"] = imp.fit_transform(df[["DIVERTED"]]).ravel().round(1)
df["CANCELLED"] = imp.fit_transform(df[["CANCELLED"]]).ravel().round(1)
df["AIR_SYSTEM_DELAY"] = imp.fit_transform(df[["AIR_SYSTEM_DELAY"]]).ravel().round(1)
df["SECURITY_DELAY"] = imp.fit_transform(df[["SECURITY_DELAY"]]).ravel().round(1)
df["AIRLINE_DELAY"] = imp.fit_transform(df[["AIRLINE_DELAY"]]).ravel().round(1)
df["LATE_AIRCRAFT_DELAY"] = imp.fit_transform(df[["LATE_AIRCRAFT_DELAY"]]).ravel().round(1)
df["WEATHER_DELAY"] = imp.fit_transform(df[["WEATHER_DELAY"]]).ravel().round(1)

#Creamos una matriz con las columnas que nos interesan
dfsmall = df[["ARRIVAL_DELAY","DIVERTED","CANCELLED","AIR_SYSTEM_DELAY",
              "SECURITY_DELAY","AIRLINE_DELAY","LATE_AIRCRAFT_DELAY","WEATHER_DELAY"]].copy()

#Creo la matriz correlacion
print("Matriz correlacion:\n\n{}".format(dfsmall.corr()))

Matriz correlacion:

                     ARRIVAL_DELAY      DIVERTED  CANCELLED  AIR_SYSTEM_DELAY  \
ARRIVAL_DELAY             1.000000 -1.649431e-05  -0.000158         -0.029125
DIVERTED                 -0.000016  1.000000e+00  -0.009581          0.000027
CANCELLED                -0.000158 -9.580963e-03   1.000000          0.000258
AIR_SYSTEM_DELAY         -0.029125  2.696601e-05   0.000258          1.000000
SECURITY_DELAY            0.112820 -8.738411e-06  -0.000084         -0.072857
AIRLINE_DELAY             0.370123  6.203747e-06   0.000059         -0.231906
LATE_AIRCRAFT_DELAY       0.262079  1.639126e-05   0.000157         -0.097807
WEATHER_DELAY             0.282422  4.927761e-07   0.000005         -0.159545

                     SECURITY_DELAY  AIRLINE_DELAY  LATE_AIRCRAFT_DELAY  \
ARRIVAL_DELAY              0.112820       0.370123             0.262079
DIVERTED                  -0.000009       0.000006             0.000016
CANCELLED                 -0.000084       0.000059             0.000157
AIR_SYSTEM_DELAY          -0.072857      -0.231906            -0.097807
SECURITY_DELAY             1.000000       0.187933            -0.011882
AIRLINE_DELAY              0.187933       1.000000            -0.067741
LATE_AIRCRAFT_DELAY       -0.011882      -0.067741             1.000000
WEATHER_DELAY             -0.034130      -0.195950            -0.045821

                     WEATHER_DELAY
ARRIVAL_DELAY         2.824224e-01
DIVERTED              4.927761e-07
CANCELLED             4.716548e-06
AIR_SYSTEM_DELAY     -1.595446e-01
SECURITY_DELAY       -3.413027e-02
AIRLINE_DELAY        -1.959503e-01
LATE_AIRCRAFT_DELAY  -4.582065e-02
WEATHER_DELAY         1.000000e+00

## Soluciones a los ejercicios para practicar

## Ejercicio 1

a) ¿Cuantos valores diferentes tiene el atributo `marital` en el conjunto de datos? Mostrad estos valores.

In [30]:
import pandas as pd
import numpy as np

data = pd.read_csv("data/bank_edited.csv", sep=";", dtype={"balance":np.float})

import numpy as np

# Con unique podemos encotrar los valors únicos

v = data.marital.unique()

print("There are {} different values in marital:\n{}".format(len(v), v))

There are 11 different values in marital:
['married' 'single' 'marrid' 'divorced' 'maried' 'sing' 'Married'
 'MARRIED' 'DIVORCED' 'Single' 'SINGLE']

 b) Unificad los atributos `marital` en los valores: "single", "married" o "divorced".

In [31]:
data.loc[(data.marital == "Married") | (data.marital == "maried") | (data.marital == "MARRIED") | 
         (data.marital == "marrid"), "marital"] = "married"
data.loc[(data.marital == "Single") | (data.marital == "SINGLE") | (data.marital == "sing"), "marital"] = "single"
data.loc[(data.marital == "DIVORCED"), "marital"] = "divorced"

# Comprobación

v = data.marital.unique()
print("There are {} different values in marital:\n{}".format(len(v), v))

There are 3 different values in marital:
['married' 'single' 'divorced']

c) Qué columnas contienen valores perdidos?

In [32]:
# Para esto usamos la función  any_isna a cada columna del dataframe 
print(data.isna().any())

age          False
job          False
marital      False
education    False
default      False
balance       True
housing      False
loan         False
contact      False
day           True
month        False
duration      True
campaign     False
pdays        False
previous     False
poutcome     False
y            False
dtype: bool

d) Calculad el primer y el tercer cuartil del atributo `balance`.

In [33]:
print((data['balance'].quantile(0.25)))
print(data['balance'].quantile(0.75))

68.0
1476.0

## Ejercicio 2

El atributo `poutcome` contiene información sobre si el cliente del banco contractó un deposito. Calula la correlacióm entre el atributo `poutcome` y el resto de atributos (usa la función `corr'). Qué variable presenta mayor correlación con 'poutcome'?

In [104]:
# Visualizamos los valores de la columna poutcome
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

data.poutcome.unique()

array(['unknown', 'failure', 'other', 'success'], dtype=object)

In [105]:
# Seleccionamos únicamente la muestras que contienen  informacióno precisa sobre el ciente contrató o no el depósito

data_pout = data[data.poutcome.isin(("failure","success"))]

# Discretizamos la columna poutcome para poder calcular la correlación 

data_pout['poutcome_cat'] = data_pout.poutcome.astype("category").cat.codes

# Calculamos la correlación con el resto de columnas 

data_pout.corr()["poutcome_cat"]

age             0.090540
balance         0.039791
day             0.009252
duration        0.142385
campaign       -0.059986
pdays          -0.276853
previous        0.023411
poutcome_cat    1.000000
Name: poutcome_cat, dtype: float64

Observad que la columna `pdays` muestra tenir mayor correlació en valor absoluto con  poutcome_cat.  Tened en cuenta que hemos asignado un 0/1 a "failure"/"succes" de manera arbitraria, así que el signo no es significtivo en este caso.

## Ejercicio 3

El módulo sklearn incluye varios datasets de ejemplo, dentro del módulo `sklearn.datasets`. Estos datasets se almacenan en formato `Bunch`, propio de sklearn. Un `Bunch` es un objeto tipo diccionario, los atributos interesantes son: `data`, con los datos en crudo, `target`, con generalmente las etiquetas de clasificación o etiquetas objetivo, `target_names`, el significado de las etiquetas, `feature_names`, el significado de las características o atributos, `DESCR` , la descripción completa del conjunto de datos.

Importa el dataset `iris` de `sklearn`. Almacena los datos este dataset como un objeto `pandas`, con los correpondientres nombres de variables. Añade la variable `target` en el dataframe con el nombre de atributo `Species` y los valors con el tipo de especie de cada muestra.

In [36]:
from sklearn import datasets
import pandas as pd
iris_bunch = datasets.load_iris()
iris_pandas = pd.DataFrame(iris_bunch['data'],columns=iris_bunch['feature_names'])
iris_pandas['Species'] = iris_bunch['target_names'][iris_bunch['target']]

In [37]:
iris_pandas.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [38]:
iris_pandas.tail()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [39]:
iris_pandas.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000